services:
  backend:
    # Вместо сборки из исходников используем готовый образ из Docker Hub
    image: sadsunnymouse/fitbuddy-backend:latest
    ports:
      - "5000:5000"
    environment:
      # Эти переменные будут переопределены в панели управления Render,
      # но мы их здесь указываем, чтобы файл был самодостаточным.
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT}
      - JWT_SECRET=${JWT_SECRET}
      - PORT=5000

  frontend:
    image: sadsunnymouse/fitbuddy-frontend:latest
    ports:
      - "3000:3000"